# GENERATED by Tests/Pickle/New-LabelFeatures.ps1 from Tests/Translation-inventory.json. Do not edit by hand.
#
# The English text as the loaded definitions hold it, read in a game started in English (-Language English).
# It comes from the Def values themselves, which is where English lives for this mod: there is no English language folder, and none is needed.
# A text that is still in the other language here is a translation the game did not apply, whatever the
# offline inventory says: a language folder the game does not find fails silently, and the offline check
# only proves that the keys resolve. Every species is a ThingDef and a PawnKindDef of the same name, so
# each step names the def type. Played only in the English pass; the twin is 07.
@en-only
Feature: the English labels and descriptions reach the loaded definitions

  Scenario: the species names and descriptions a player reads
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "description" as "Nobody knows what the Ebbbs are, or where they originate from. Scientists have been examining these things for decades. Are they a new species of rodent? Maybe they're a magical being brought to this plane via some greater power? It's a mystery, yet the only thing that's certain, is that they really, really like cheese."
    Then Ebbbs Renew: the ThingDef "Beee" reads "label" as "beee"
    Then Ebbbs Renew: the ThingDef "Beee" reads "description" as "The Beees, natural predators of the Ebbbs. Their hats are cool."
    Then Ebbbs Renew: the ThingDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" reads "description" as "A messy, chaotic amalgamation of ebbbs. It writhes and gurgles in a horrible tangle of tentacles and goo."
    Then Ebbbs Renew: the ThingDef "Goliebbb" reads "label" as "goliebbb"
    Then Ebbbs Renew: the ThingDef "Goliebbb" reads "description" as "A horrifying monstrosity, the Goliebbb is a terrifying, unstable colossus that devours everything in its path. If you see it, it most definitely has seen you."
    Then Ebbbs Renew: the ThingDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the ThingDef "Ebbberration" reads "description" as "The Ebbberration, a freak of nature mimicking humans. One of its appendages has turned into a strong scythe-like claw, able to cut through tough steel like butter. (Original design by ReineOfCloves)"
    Then Ebbbs Renew: the ThingDef "Drebbbd" reads "label" as "drebbbd"
    Then Ebbbs Renew: the ThingDef "Drebbbd" reads "description" as "When an Ebbb goes insane, it starts forcibly and violently assimilating with any other Ebbbs it comes across. This phenomenon is called a Drebbbd."
    Then Ebbbs Renew: the ThingDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" reads "description" as "The Bebbbholder, named after the fictional Beholders due to their floating body and many eyes. These creatures emanate an aura of some kind, it is not sure what the purpose of this aura is, but those in close proximity for an extended amount of time to a Bebbbholder have described sensations of fear and dread."
    Then Ebbbs Renew: the ThingDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the ThingDef "Crebbb" reads "description" as "A 3-legged monster that is surprisingly friendly. As a herbivore, its main source of nutritian is plantlife, as such it rarely attacks people and is generally more docile than the other Ebbbs."
    Then Ebbbs Renew: the ThingDef "Thrumebbb" reads "label" as "thrumebbb"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" reads "description" as "A gross mockery of the Universe's most graceful creature, the Thrumebbb is an amalgamation of Ebbbs that has somehow gained a semblance of intelligence. It is foul, and reeks of death. Beware, for it does not eat trees."

  Scenario: the labels of what the species leave behind
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "Filth_BloodEbbb" reads "label" as "blood"
    Then Ebbbs Renew: the ThingDef "Leather_Ebbb" reads "label" as "ebbb leather"
    Then Ebbbs Renew: the ThingDef "Leather_Ebbb" reads "description" as "Tanned, dried, scraped ebbb leather. It feels wrong to touch this..."
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" reads "label" as "thrumebbb horn"
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" reads "description" as "A thrumebbb's horn. It's a gloopy mess, constantly oozing disgusting black goo. Useless for anything except for being a trophy."
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "race.meatLabel" as "ebbb meat"

  Scenario: the kinds and their life stages
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the PawnKindDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the PawnKindDef "Beee" reads "label" as "beee"
    Then Ebbbs Renew: the PawnKindDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the PawnKindDef "Goliebbb" reads "label" as "goliebbb"
    Then Ebbbs Renew: the PawnKindDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the PawnKindDef "Drebbbd" reads "label" as "drebbbd"
    Then Ebbbs Renew: the PawnKindDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the PawnKindDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" reads "label" as "thrumebbb"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" has a life stage whose label is "thrumebbb spawn"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" has a life stage whose labelPlural is "thrumebbb calves"

  Scenario: the melee attacks in the combat log
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" has a tool labelled "point"
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" has a tool labelled "base"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "right appendage"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "right appendage"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "right appendage"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "right appendage"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "right claw"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "left appendage"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "right appendage"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" has a tool labelled "tentacles"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Crebbb" has a tool labelled "front legs"
    Then Ebbbs Renew: the ThingDef "Crebbb" has a tool labelled "head"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "horn"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "left foot"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "right foot"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "head"

  Scenario: the body plans in the health tab
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the BodyDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "left eye"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "right eye"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "left shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "left tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "left appendage"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "right shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "right tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "right appendage"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "left leg"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "right leg"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "left eye"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "right eye"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "left shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "left tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "left appendage"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "right shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "right tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "right appendage"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "left tentacle cluster"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "right tentacle cluster"
    Then Ebbbs Renew: the BodyDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "eye"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "left shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "left tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "left appendage"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "right shoulder"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "right tentacle"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "right claw"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "left leg"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "right leg"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "eye"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "left tentacle cluster"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "right tentacle cluster"
    Then Ebbbs Renew: the BodyDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "eye"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "left leg"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "right leg"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "back leg"
