# GENERATED by Tests/Pickle/New-LabelFeatures.ps1 from Tests/Translation-inventory.json. Do not edit by hand.
#
# The French text as the loaded definitions hold it, read in a game started in French (-Language French).
# It comes from Mod/Languages/French.
# A text that is still in the other language here is a translation the game did not apply, whatever the
# offline inventory says: a language folder the game does not find fails silently, and the offline check
# only proves that the keys resolve. Every species is a ThingDef and a PawnKindDef of the same name, so
# each step names the def type. Played only in the French pass; the twin is 06.
@fr-only
Feature: the French labels and descriptions reach the loaded definitions

  Scenario: the species names and descriptions a player reads
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "description" as "Personne ne sait ce que sont les ebbbs, ni d'où ils viennent. Les scientifiques étudient ces choses depuis des décennies. S'agit-il d'une nouvelle espèce de rongeur ? Peut-être sont-ils des êtres magiques amenés dans ce monde par une puissance supérieure ? Le mystère reste entier. Une seule chose est certaine : ils aiment vraiment, vraiment beaucoup le fromage."
    Then Ebbbs Renew: the ThingDef "Beee" reads "label" as "beee"
    Then Ebbbs Renew: the ThingDef "Beee" reads "description" as "Les beees sont les prédateurs naturels des ebbbs. Leurs chapeaux sont chouettes."
    Then Ebbbs Renew: the ThingDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" reads "description" as "Un amalgame informe et chaotique d'ebbbs. Il se tortille et gargouille dans un horrible enchevêtrement de tentacules et de glu."
    Then Ebbbs Renew: the ThingDef "Goliebbb" reads "label" as "goliebbb"
    Then Ebbbs Renew: the ThingDef "Goliebbb" reads "description" as "Monstruosité terrifiante, le goliebbb est un colosse instable qui dévore tout sur son passage. Si vous le voyez, il vous a très certainement déjà vu."
    Then Ebbbs Renew: the ThingDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the ThingDef "Ebbberration" reads "description" as "L'ebbberration est une aberration de la nature qui imite les humains. L'un de ses appendices s'est transformé en une puissante griffe en forme de faux, capable de trancher l'acier le plus résistant comme du beurre. (Concept original de ReineOfCloves)"
    Then Ebbbs Renew: the ThingDef "Drebbbd" reads "label" as "drebbbd"
    Then Ebbbs Renew: the ThingDef "Drebbbd" reads "description" as "Lorsqu'un ebbb devient fou, il se met à fusionner de force et avec violence avec tous les autres ebbbs qu'il croise. Ce phénomène est appelé drebbbd."
    Then Ebbbs Renew: the ThingDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" reads "description" as "Le bebbbholder doit son nom aux beholders de fiction, auxquels il ressemble par son corps flottant et ses nombreux yeux. Ces créatures dégagent une sorte d'aura dont on ignore la fonction, mais ceux qui sont restés longtemps à proximité d'un bebbbholder ont décrit des sensations de peur et d'effroi."
    Then Ebbbs Renew: the ThingDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the ThingDef "Crebbb" reads "description" as "Un monstre à trois pattes étonnamment amical. Herbivore, il se nourrit principalement de végétaux, si bien qu'il attaque rarement les gens et se montre généralement plus docile que les autres ebbbs."
    Then Ebbbs Renew: the ThingDef "Thrumebbb" reads "label" as "thrumebbb"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" reads "description" as "Parodie grotesque de la créature la plus gracieuse de l'univers, le thrumebbb est un amalgame d'ebbbs qui a acquis, on ne sait comment, un semblant d'intelligence. Il est répugnant et empeste la mort. Méfiez-vous : il ne mange pas les arbres."

  Scenario: the labels of what the species leave behind
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "Filth_BloodEbbb" reads "label" as "sang"
    Then Ebbbs Renew: the ThingDef "Leather_Ebbb" reads "label" as "cuir d'ebbb"
    Then Ebbbs Renew: the ThingDef "Leather_Ebbb" reads "description" as "Du cuir d'ebbb tanné, séché et raclé. Le toucher provoque une sensation de malaise..."
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" reads "label" as "corne de thrumebbb"
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" reads "description" as "Une corne de thrumebbb. Cette masse visqueuse suinte sans cesse une glu noire répugnante. Elle ne sert à rien, si ce n'est de trophée."
    Then Ebbbs Renew: the ThingDef "Ebbb" reads "race.meatLabel" as "viande d'ebbb"

  Scenario: the kinds and their life stages
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the PawnKindDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the PawnKindDef "Beee" reads "label" as "beee"
    Then Ebbbs Renew: the PawnKindDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the PawnKindDef "Goliebbb" reads "label" as "goliebbb"
    Then Ebbbs Renew: the PawnKindDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the PawnKindDef "Drebbbd" reads "label" as "drebbbd"
    Then Ebbbs Renew: the PawnKindDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the PawnKindDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" reads "label" as "thrumebbb"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" has a life stage whose label is "petit thrumebbb"
    Then Ebbbs Renew: the PawnKindDef "Thrumebbb" has a life stage whose labelPlural is "petits thrumebbbs"

  Scenario: the melee attacks in the combat log
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" has a tool labelled "pointe"
    Then Ebbbs Renew: the ThingDef "ThrumebbbHorn" has a tool labelled "base"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "appendice droit"
    Then Ebbbs Renew: the ThingDef "Ebbb" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "appendice droit"
    Then Ebbbs Renew: the ThingDef "Beee" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "appendice droit"
    Then Ebbbs Renew: the ThingDef "Ebbbomination" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "appendice droit"
    Then Ebbbs Renew: the ThingDef "Goliebbb" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "griffe droite"
    Then Ebbbs Renew: the ThingDef "Ebbberration" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "appendice gauche"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "appendice droit"
    Then Ebbbs Renew: the ThingDef "Drebbbd" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" has a tool labelled "tentacules"
    Then Ebbbs Renew: the ThingDef "Bebbbholder" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Crebbb" has a tool labelled "pattes avant"
    Then Ebbbs Renew: the ThingDef "Crebbb" has a tool labelled "tête"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "corne"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "pied gauche"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "pied droit"
    Then Ebbbs Renew: the ThingDef "Thrumebbb" has a tool labelled "tête"

  Scenario: the body plans in the health tab
    Given Ebbbs Renew: the game has finished starting
    And the main menu is open
    Then Ebbbs Renew: the BodyDef "Ebbb" reads "label" as "ebbb"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "œil gauche"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "œil droit"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "épaule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "tentacule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "appendice gauche"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "épaule droite"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "tentacule droit"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "appendice droit"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "patte gauche"
    Then Ebbbs Renew: the BodyDef "Ebbb" has a part labelled "patte droite"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" reads "label" as "ebbbomination"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "œil gauche"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "œil droit"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "épaule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "tentacule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "appendice gauche"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "épaule droite"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "tentacule droit"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "appendice droit"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "faisceau de tentacules gauche"
    Then Ebbbs Renew: the BodyDef "Ebbbomination" has a part labelled "faisceau de tentacules droit"
    Then Ebbbs Renew: the BodyDef "Ebbberration" reads "label" as "ebbberration"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "œil"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "épaule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "tentacule gauche"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "appendice gauche"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "épaule droite"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "tentacule droit"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "griffe droite"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "patte gauche"
    Then Ebbbs Renew: the BodyDef "Ebbberration" has a part labelled "patte droite"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" reads "label" as "bebbbholder"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "œil"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "faisceau de tentacules gauche"
    Then Ebbbs Renew: the BodyDef "Bebbbholder" has a part labelled "faisceau de tentacules droit"
    Then Ebbbs Renew: the BodyDef "Crebbb" reads "label" as "crebbb"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "œil"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "patte gauche"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "patte droite"
    Then Ebbbs Renew: the BodyDef "Crebbb" has a part labelled "patte arrière"
