<#
.SYNOPSIS
  Writes 06-labels-en.feature and 07-labels-fr.feature from Tests/Translation-inventory.json.

.DESCRIPTION
  The inventory is the reviewed list of the 104 texts this mod owns, with the English source and the French
  entry of each. The two features assert that each one reaches the loaded definitions, in a game started in
  the language of the pass: the offline checkers prove the keys resolve, and only a running game shows that
  the translation was applied.

  Every inventory key has to fit one of five shapes. A key that fits none stops the script, so a new kind of
  text cannot be silently left out of the features.

    <Def>.label | description | labelPlural      the value read off the def by its type
    <Def>.race.meatLabel                          the same, on a dotted path
    <Def>.tools.<handle>.label                    a melee tool of that label exists
    <Def>.corePart. ... .customLabel              a body part of that label exists
    <Def>.lifeStages.<handle>.label | labelPlural a life stage of that value exists

  Rerun it after any change to the inventory, then Check-Steps.ps1.

.EXAMPLE
  powershell -NoProfile -ExecutionPolicy Bypass -File Tests/Pickle/New-LabelFeatures.ps1
#>
$ErrorActionPreference = 'Stop'
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$inventory = Get-Content -LiteralPath (Join-Path $root 'Tests/Translation-inventory.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$features = Join-Path $PSScriptRoot 'Mod/Pickle/Features'

function Get-Step($entry, [string]$text) {
    $name, $rest = $entry.key -split '\.', 2
    $type = $entry.type
    if ($text -match '["\\]') { throw "The text '$text' of $($entry.key) holds a quote or a backslash, which a step argument cannot carry unescaped." }
    if ($rest -in 'label', 'description', 'labelPlural', 'race.meatLabel') {
        return "Ebbbs Renew: the $type `"$name`" reads `"$rest`" as `"$text`""
    }
    if ($type -eq 'ThingDef' -and $rest -match '^tools\.[^.]+\.label$') {
        return "Ebbbs Renew: the ThingDef `"$name`" has a tool labelled `"$text`""
    }
    if ($type -eq 'BodyDef' -and $rest -match '^corePart\..+\.customLabel$') {
        return "Ebbbs Renew: the BodyDef `"$name`" has a part labelled `"$text`""
    }
    if ($type -eq 'PawnKindDef' -and $rest -match '^lifeStages\.[^.]+\.(label|labelPlural)$') {
        return "Ebbbs Renew: the PawnKindDef `"$name`" has a life stage whose $($Matches[1]) is `"$text`""
    }
    throw "The key $($entry.key) of type $type fits none of the shapes this script knows."
}

# The order the player meets the texts in, and the scenario each group becomes.
$groups = @(
    @{ Title = 'the species names and descriptions a player reads';  Match = { $_.type -eq 'ThingDef' -and $_.key -match '^[^.]+\.(label|description)$' -and $_.key -notmatch '^(Leather_Ebbb|ThrumebbbHorn|Filth_BloodEbbb)\.' } },
    @{ Title = 'the labels of what the species leave behind';        Match = { $_.type -eq 'ThingDef' -and $_.key -notmatch '\.tools\.' -and ($_.key -match '^(Leather_Ebbb|ThrumebbbHorn|Filth_BloodEbbb)\.' -or $_.key -match '\.race\.meatLabel$') } },
    @{ Title = 'the kinds and their life stages';                    Match = { $_.type -eq 'PawnKindDef' } },
    @{ Title = 'the melee attacks in the combat log';                Match = { $_.type -eq 'ThingDef' -and $_.key -match '\.tools\.' } },
    @{ Title = 'the body plans in the health tab';                   Match = { $_.type -eq 'BodyDef' } }
)

$seen = @{}
foreach ($language in 'english', 'french') {
    $tag = if ($language -eq 'english') { '@en-only' } else { '@fr-only' }
    $twin = if ($language -eq 'english') { '07' } else { '06' }
    $file = if ($language -eq 'english') { '06-labels-en.feature' } else { '07-labels-fr.feature' }
    $where = if ($language -eq 'english') { 'the Def values themselves, which is where English lives for this mod: there is no English language folder, and none is needed' } else { 'Mod/Languages/French' }
    $started = if ($language -eq 'english') { 'English' } else { 'French' }
    $body = New-Object System.Text.StringBuilder
    [void]$body.AppendLine("# GENERATED by Tests/Pickle/New-LabelFeatures.ps1 from Tests/Translation-inventory.json. Do not edit by hand.")
    [void]$body.AppendLine("#")
    [void]$body.AppendLine("# The $started text as the loaded definitions hold it, read in a game started in $started (-Language $started).")
    [void]$body.AppendLine("# It comes from $where.")
    [void]$body.AppendLine("# A text that is still in the other language here is a translation the game did not apply, whatever the")
    [void]$body.AppendLine("# offline inventory says: a language folder the game does not find fails silently, and the offline check")
    [void]$body.AppendLine("# only proves that the keys resolve. Every species is a ThingDef and a PawnKindDef of the same name, so")
    [void]$body.AppendLine("# each step names the def type. Played only in the $started pass; the twin is $twin.")
    [void]$body.AppendLine($tag)
    [void]$body.AppendLine("Feature: the $started labels and descriptions reach the loaded definitions")
    $count = 0
    foreach ($group in $groups) {
        $entries = @($inventory | Where-Object $group.Match)
        if ($entries.Count -eq 0) { throw "The group '$($group.Title)' matches nothing." }
        [void]$body.AppendLine('')
        [void]$body.AppendLine("  Scenario: $($group.Title)")
        [void]$body.AppendLine('    Given the main menu is open')
        foreach ($entry in $entries) {
            $seen[$entry.key + '|' + $entry.type] = $true
            $text = $entry.$language
            [void]$body.AppendLine('    Then ' + (Get-Step $entry $text))
            $count++
        }
    }
    # The generated text is French in one file: write UTF-8 without a byte order mark, with LF endings.
    $path = Join-Path $features $file
    [IO.File]::WriteAllText($path, ($body.ToString() -replace "`r`n", "`n"), (New-Object System.Text.UTF8Encoding($false)))
    Write-Host ("{0}: {1} steps" -f $file, $count)
}

$missed = @($inventory | Where-Object { -not $seen[$_.key + '|' + $_.type] })
if ($missed.Count -gt 0) { throw ("{0} inventory entries fall in no scenario: {1}" -f $missed.Count, (($missed | Select-Object -First 3 | ForEach-Object key) -join ', ')) }
Write-Host ("All {0} inventory entries are covered, in each language." -f $inventory.Count)
